# Scraping NUFORC Data

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as bs
import random

## Define Functions

In [4]:
def get_all_source_html():
    states_list = ("AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","HI","IA","ID",
               "IL","IN","KS","KY","LA","MA","MD","ME","MI","MN","MO","MS","MT","NC",
               "ND","NE","NH","NJ","NM","NV","NY", "OH","OK","OR","PA","RI","SC",
               "SD","TN","TX","UT","VA","VT","WA","WI","WV","WY")
    webpages = []
    for state in states_list:
        source_html = requests.get(f'http://www.nuforc.org/webreports/ndxl{state}.html').text
        webpages.append(source_html)
    return webpages
    
def parse_html(source_html):
    soup = bs(source_html,'html.parser')
    all_text = soup.get_text()
    file_start = all_text.index('Date / Time')
    html = all_text[file_start:]
    return(html)

def make_list(file):
    split = file.split('\n')         # Splits all_text string by whitespace

    for element in split:                # Unfortunately we need to remove the empty strings from the
        if element == '':                # list since they don't ONLY represent blank cells here
            split.remove(element)    
    columns = split[0:7]                 # Grab Columns
    data = split[7:]                     # Grab Data. Data is not usable yet due to the fact that 
                                         # empty cells are not being read.
    return([columns,data])   

def identify_rows(data):
    rows = []
    for value in range(len(data)):       # Searches the data for entries containing ':' after '/'.
        pieces = data[value].split('/')  # Safe to assume only datetime values will follow this
        if ':' in pieces[-1] and len(pieces) == 3:            # format, so we can insert a placeholder string before them
            rows.append('DATETIME')      # to mark where rows begin.
        rows.append(data[value])
    rows.append('DATETIME')
    return rows

def identify_rows_redux(data):
    rows = []
    for value in range(len(data)):       # Searches the data for entries containing ':' after '/'.
        pieces = data[value].split('/')  # Safe to assume only datetime values will follow this
        if ':' in pieces[-1] and len(pieces) == 3:            # format, so we can insert a placeholder string before them
            rows.append('DATETIME')      # to mark where rows begin.
        if val_decider(data[value-1]) == 'Posted' and val_decider(data[value]) == 'Posted':
            rows.append('DATETIME')
        if data[value] != '':
            rows.append(data[value])
    rows.append('DATETIME')
    return rows

def identify_rows_redux_deux(data):
    rows =['DATETIME']
    for value in range(len(data)):
        rows.append(data[value])
        if valid_posted(data[value]) and valid_datetime(data[value+1]):
            rows.append('DATETIME')
        elif valid_posted(data[value]) and valid_posted(data[value+1]):
            rows.append('DATETIME')
    return rows

def valid_datetime(value):
    valid_datetime = False
    pieces = value.split('/')
    if ':' in pieces[-1] and len(pieces) == 3 and len(value) < 15:
        valid_datetime = True
    return valid_datetime


def valid_shape(value): 
    shape_vals = ['Circle', 'Unknown', 'Cigar', 'Other', 'Light', 'Fireball', 'Rectangle',
                    'Teardrop','Oval', 'Disk', 'Sphere', 'Triangle', 'Formation', 'Cross', 'Diamond',
                    'Changing', 'Chevron', 'Egg', 'Flash', 'Cylinder', 'Cone', 'Delta', 'Star']
    valid_shape = False
    if value in shape_vals:
        valid_shape = True
    return valid_shape

def valid_duration(value):
    valid_duration = False
    if value == '':
        return valid_duration
    if value[0] in ['<','>','~']:
        valid_duration = True
        return valid_duration
    try:
        int(value[0])
    except:
        return valid_duration    # as False
    if '/' in value:
        return valid_duration    # as False
    valid_duration = True
    return valid_duration        # set to True if starts with int and has no '/'
    
    
def valid_summary(value):
    valid_summary = False
    if len(value.split(' ')) > 2:
        valid_summary = True
    return valid_summary
        
def valid_posted(value):
    valid_posted = False    
    dates = value.split('/')
    if len(dates) != 3 or len(value) > 10:
        return valid_posted
    for date in dates:
        if len(date) > 2:
            return valid_posted
    valid_posted = True
    return valid_posted
    

def val_decider(value):
    val_type = 'no_type'
    if valid_shape(value):
        val_type = 'Shape'
    elif valid_duration(value):
        val_type = 'Duration'
    elif valid_summary(value):
        val_type = 'Summary'
    elif valid_posted(value):
        val_type = 'Posted'
    return val_type

def identify_columns(columns, rows):
    rows_list = []
    for i in range(len(rows)):
        if rows[i] == 'DATETIME' and i != len(rows)-1:
            curr_row = []                       # Initialize current row as list. List values follow cols.
            curr_row.append(rows[i+1])          # Add the date/time val to curr_row
            curr_row.append(rows[i+2])          # Add the city val to curr_row
            curr_row.append(rows[i+3])          # Add the state val to curr_row
            row_try = 0
            for j in [3,4,5,6]:                 # Add other values to columns if they exist
                if val_decider(rows[i+row_try+4]) == columns[j]:
                    curr_row.append(rows[i+row_try+4])
                    row_try += 1
                else:
                    curr_row.append('')
            rows_list.append(curr_row)
    return rows_list
    # When we make the read me, emphasize the idea of incrementing columns w/o incrementing
    # val_decider to stay pointed at the current value / not skip it.

def identify_columns_redux(columns,rows):
    rows_list = []
    for i in range(len(rows)):
        if rows[i] == 'DATETIME' and i != len(rows)-1:
            count = 0
            curr_row = ['','','','','','','']
            while rows[i+1+count] != 'DATETIME' and count < 7:
                curr_row[count] = rows[i+1+count]
                count+=1
            for value in curr_row:
                if valid_posted(value):
                    end_of_row = curr_row.index(value)
            if end_of_row != 6:
                    curr_row[6] = curr_row[end_of_row]
                    curr_row[end_of_row] = '' 
            rows_list.append(curr_row)
    return rows_list
    

def identify_columns_redux_deux(columns,rows):
    rows_list = []
    for i in range(len(rows)):
        if rows[i] == 'DATETIME' and i != len(rows)-1:
            count = 0
            curr_row = []
            while val_decider(rows[i+count]) != 'Posted' and count < 7:
                curr_row.append(rows[i+1+count])
                count += 1
            if len(curr_row) < 7:
                while len(curr_row) < 7:
                    curr_row.append('')
                for j in [3,4,5,6]:
                    if val_decider(curr_row[j]) != 'no_type':
                        col_type = val_decider(curr_row[j])
                        if col_type != columns[j]:
                            temp = curr_row[columns.index(col_type)]
                            curr_row[columns.index(col_type)] = curr_row[j] 
                            curr_row[j] = temp
            if val_decider(curr_row[-1]) != 'Posted':
                for val in range(len(curr_row)):
                    if val_decider(curr_row[val]) == 'Posted':
                        temp = curr_row[val]
                        curr_row[val] = ''
                        curr_row[-1] = temp
            if val_decider(curr_row[3]) != 'Shape':
                curr_row[3] = ''
            if val_decider(curr_row[4]) != 'Duration':
                curr_row[4] = ''
            if val_decider(curr_row[5]) != 'Summary':
                curr_row[5] = ''
            if len(curr_row[1])>3 and len(curr_row[2]) == 2:
                rows_list.append(curr_row)
    return rows_list

def merge_csvs(df_list):
    none = []
    return none

## Main Functionality

In [5]:
webpages = get_all_source_html()

In [6]:
list_of_data = []

columns = ['Date / Time', 'City', 'State', 'Shape', 'Duration', 'Summary', 'Posted']

for webpage in webpages:
    html = parse_html(webpage)

    raw_data = make_list(html)
    columns = raw_data[0]

    rows = identify_rows_redux_deux(raw_data[-1])

    clean_data = identify_columns_redux_deux(columns,rows)

    list_of_data.append(clean_data)
    print(f'appended data for {clean_data[1][2]} \n   Sample Row: {clean_data[random.randint(0,100)]}')
print(len(list_of_data))

appended data for AK
   Sample Row: ['2/26/17 22:51', 'Wasilla', 'AK', 'Oval', '2-3 minutes', '3 low and slow moving pulsating orange/reddish orbs.', '3/10/17']
appended data for AL
   Sample Row: ['10/8/21 22:00', 'Albertville', 'AL', 'Fireball', '5 second', 'The object was round and it looked like an orb or fireball , it had green color to it like a weld spark. I saw it for about 5 seconds w', '10/19/21']
appended data for AR
   Sample Row: ['9/19/21 05:15', 'Jonesboro', 'AR', '', '', 'MADAR Node 143', '10/19/21']
appended data for AZ
   Sample Row: ['12/3/21 18:30', 'Sedona', 'AZ', '', '50 or more lights miles long in a line across the night sky. Lasted a couple minutes then disappeared from the head to tail systematica', '', '12/19/21']
appended data for CA
   Sample Row: ['12/10/21 00:00', 'Tecopa', 'CA', 'Rectangle', '', 'seen dark rectangle moving slowly thru the sky. There was no illumination of light. Kind of like a bird swam or bugs but rectangle.', '12/19/21']
appended data for CO
   Sample Row: ['2/11/21 05:55', 'Evergreen', 'CO', 'Light', '10 minutes', 'Massive string of slow/standard-moving lights in single-file line consumes entire sky ((Starlink satellites??))', '3/2/21']
appended data for CT
   Sample Row: ['4/5/21 20:51', 'Norwalk', 'CT', '', '', 'MADAR Node 103', '4/23/21']
appended data for DC
   Sample Row: ['7/25/12 21:30', 'Washington', 'DC', 'Changing', '10-15 minutes', '', '8/19/12']
appended data for DE
   Sample Row: ['11/13/20 17:30', 'Wyoming', 'DE', '', '10 min', '', '12/23/20']
appended data for FL
   Sample Row: ['5/9/21 22:25', 'Port Charlotte', 'FL', 'Sphere', '11 seconds', 'My home security camera captured two spheres of light hovering around. It appeared as if they were aware of each other. Then the bigges', '5/20/21']
appended data for GA
   Sample Row: ['10/18/20 05:30', 'Rocky Face', 'GA', 'Sphere', '2 hours', 'I first thought it was a very bright star then realized it was to low in the dark night sky to be a star. I got my binoculars and disco', '12/23/20']
appended data for HI
   Sample Row: ['10/24/20 22:00', 'Kula', 'HI', 'Formation', '20 seconds', 'A group of light in the shape of a gigantic ship floating by in space upper Kula.', '12/23/20']
appended data for IA
   Sample Row: ['7/25/20 23:00', 'Shellsburg', 'IA', 'Light', '', 'As we were looking for the comet I noticed a light that was moving erratically back forth up down a little to the east of the dipper th', '7/31/20']
appended data for ID
   Sample Row: ['8/7/20 09:40', 'Boise', 'ID', 'Disk', '<2 minutes', 'Headed  east bound on I84 at about 940am. Saw 2 extremely bright orbs in the sky. They were stationary. On winked out in front of me. A', '8/20/20']
appended data for IL
   Sample Row: ['9/21/20 21:05', 'Vernon Hills', 'IL', 'Light', '1 second', 'Green ball of light blasts forward and disappears in Vernon Hills, Illinois.', '11/5/20']
appended data for IN
   Sample Row: ['10/18/20 05:10', 'Fishers', 'IN', '', '', 'MADAR Node 84', '12/23/20']
appended data for KS
   Sample Row: ['10/3/20 15:00', 'Rossville', 'KS', 'Sphere', '1 minute', 'White spheres spotted in Rossville Kansas', '11/5/20']
appended data for KY
   Sample Row: ['9/2/21 14:15', 'In flight', 'KY', 'Cross', '10 seconds', 'Inverted Y-shaped object seen from commercial aircraft at 28K ft', '10/19/21']
appended data for LA
   Sample Row: ['5/22/21 22:08', 'Bossier', 'LA', 'Circle', '', 'UFO over Barksdale…', '7/31/21']
appended data for MA
   Sample Row: ['12/3/21 16:30', 'Southbridge', 'MA', 'Other', '', 'We followed a bright white star and at closer range saw an unidentifiable hovering aircraft; it traveled far in the blink of an eye.', '12/19/21']
appended data for MD
   Sample Row: ['9/7/20 12:00', 'Ocean City', 'MD', 'Diamond', '>2 hours', 'White diamond out over ocean in daylight... hovering  (over 2 hours)', '11/5/20']
appended data for ME
   Sample Row: ['6/23/20 23:00', 'Greenville', 'ME', 'Light', '~15 minutes', 'On a starry summer night in Maine my family and I observed over 50 lights very high up in the night sky ((Starlink satellites??', '3/2/21']
appended data for MI
   Sample Row: ['8/22/20 18:30', 'Madison Heights', 'MI', 'Circle', '10 minutes', 'Slowly traveling from NNW towards SSE at approximately 95,000 feet. Whole object randomly flickered bright then dull, due to either, th', '8/27/20']
appended data for MN
   Sample Row: ['5/7/20 23:10', 'Cottage Grove', 'MN', 'Circle', '3 seconds', 'Driving North on Chemolite Rd. In front and to the left of me I see a shooting star-like object nosediving towards the ground.', '6/25/20']
appended data for MO
   Sample Row: ['2/1/21 15:36', 'Springfield', 'MO', '', '', 'MADAR Node 36', '3/2/21']
appended data for MS
   Sample Row: ['2/23/18 10:45', 'Biloxi', 'MS', 'Oval', '5 minutes', 'Saw oval, white flying object traveling from Southeast to Northwest.  Passed over the Palace Casino.', '3/2/18']
appended data for MT
   Sample Row: ['11/13/20 23:11', 'Belgrade', 'MT', '', '5.00', '', '12/23/20']
appended data for NC
   Sample Row: ['10/26/21 20:00', 'Matthews', 'NC', 'Fireball', '45 seconds', 'Fireball appeared to expand and retract, darting multidirectionally for (+\\-) 45 seconds.', '11/15/21']
appended data for ND
   Sample Row: ['12/23/19 11:41', 'Valley City', 'ND', '', '', 'MADAR Node  93', '1/31/20']
appended data for NE
   Sample Row: ['4/18/20 21:00', 'Omaha', 'NE', 'Formation', '40 minutes', 'Moving star like Line formation.  ((Starlink satellites?))', '6/25/20']
appended data for NH
   Sample Row: ['8/25/20 09:10', 'Windham', 'NH', 'Triangle', '1 minute', 'Ufo seen august 25th 2020!', '8/27/20']
appended data for NJ
   Sample Row: ['3/13/21 22:00', 'Glen Ridge', 'NJ', 'Triangle', '20 seconds', 'Lighted, Triangle shaped objects flying at night, slow them very fast', '4/23/21']
appended data for NM
   Sample Row: ['7/19/20 23:05', 'Las Vegas', 'NM', 'Triangle', '12 minutes', '((NUFORC Note:  Witness provides no information about incident.  PD))', '7/31/20']
appended data for NV
   Sample Row: ['11/22/20 06:47', 'LAS VEGAS', 'NV', 'Changing', '10 MINUTES', 'I personally witnessed and took 15 crystal clear photos of a Green Glowing Spaceship and a Robot-Alien-Angel = Being ?', '12/23/20']
appended data for NY
   Sample Row: ['8/9/21 23:13', 'Elizabethtown', 'NY', '', '', 'MADAR Node 168', '10/19/21']
appended data for OH
   Sample Row: ['10/31/20 00:00', 'Georgetown', 'OH', 'Circle', '', '((NUFORC Note:  Witnes provides no information.  PD))', '12/23/20']
appended data for OK
   Sample Row: ['7/28/20 21:00', 'Pauls Valley', 'OK', 'Circle', '30 minutes', 'The objects I saw were orange, flashing, moving at incredible speeds, and didn’t look like anything I’ve ever seen before.', '7/31/20']
appended data for OR
   Sample Row: ['5/16/21 22:40', 'Keizer', 'OR', 'Circle', '5 minutes or longer', 'This was either a formation or a single craft with many lights on the outside. It was moving very slowly across the sky above my house.', '5/20/21']
appended data for PA
   Sample Row: ['3/15/21 06:35', 'Windber', 'PA', 'Circle', '15 minutes', 'Object was circular and was bright blue in color and was moving left to right, hovering above the tree line in the northern sky as the', '3/31/21']
appended data for RI
   Sample Row: ['5/25/19 12:00', 'Cranston', 'RI', 'Circle', '10-15 seconds', 'Circular looking UFO comes out of a chemtrail line after plane sprays over my house may 25 12:02 PM 2019', '6/7/19']
appended data for SC
   Sample Row: ['9/16/21 23:30', 'Cherry Grove', 'SC', 'Sphere', '30 seconds', 'Orange orb saw by three people that suddenly vanished away from us.', '10/19/21']
appended data for SD
   Sample Row: ['12/5/20 19:03', 'Huron', 'SD', 'Formation', '3 min', 'Line of moving lights in sky', '12/23/20']
appended data for TN
   Sample Row: ['11/12/20 18:20', 'Knoxville', 'TN', 'Other', '8-10 minutes', 'I saw eight independent, irregular-moving glowing objects cross the night sky.', '12/23/20']
appended data for TX
   Sample Row: ['6/3/21 09:45', 'El Paso', 'TX', 'Light', '15 seconds', 'Bright light moving at extremely fast speeds over Mount Cristo Rey', '7/31/21']
appended data for UT
   Sample Row: ['10/11/21 13:34', 'Vernal', 'UT', '', '', 'MADAR Node 181', '11/15/21']

appended data for VA
   Sample Row: ['2/25/21 06:15', 'Richmond', 'VA', 'Changing', '', 'Indeterminable Orb In Early Morning Sky, Richmond VA', '3/2/21']
appended data for VT
   Sample Row: ['1/20/18 01:00', 'Burlington', 'VT', 'Sphere', '30 seconds', 'three red orbs views from the ethan allen tower.  ((anonymous report))', '2/25/20']
appended data for WA
   Sample Row: ['8/31/21 20:35', 'Spokane', 'WA', 'Fireball', '5 seconds', 'Orange ball of light heading east, fast, silent, then disappeared', '9/7/21']
appended data for WI
   Sample Row: ['1/20/21 20:00', 'Stevens point', 'WI', 'Circle', '1 minute', 'Driving southbound on I-39 in Stevens Point we witnessed 6 circular large glowing lights that seemed relatively close. Two were to the', '3/2/21']
appended data for WV
   Sample Row: ['7/19/20 22:00', 'Hico', 'WV', 'Triangle', '1 minute', 'Triangle of lights', '7/23/20']
appended data for WY
   Sample Row: ['11/11/18 17:58', 'Evanston', 'WY', 'Circle', '18:00', 'When I said, "Hello," the craft stopped and lit up.', '11/24/18']
51

In [56]:
huge_list = []
for data in list_of_data:
    for row in data:
        huge_list.append(row)

df = pd.DataFrame(huge_list)
df.columns = columns
df.head(100)

,Date / Time,City,State,Shape,Duration,Summary,Posted
0,11/20/21 01:00,Willow,AK,Unknown,,I told my son not to shoot it that it was bigg...,12/19/21
1,10/29/21 09:25,Soldotna,AK,Circle,3 minutes,Shiny metallic craft in morning sunlight,11/15/21
2,10/29/21 09:25,Soldotna,AK,Circle,3 minutes,Shiny metallic craft in morning sunlight.,11/15/21
3,9/5/21 23:00,Fairbanks,AK,Sphere,2 minutes,Fairbanks PD sees UFO,10/19/21
4,3/17/21 23:00,Chugiak,AK,Light,2 minutes,Blue lights in sky,3/31/21
...,...,...,...,...,...,...,...
95,12/31/16 23:50,Anchorage,AK,Fireball,20 minutes,"Three bright orange orbs, exhibiting odd fligh...",1/6/17
96,12/31/16 23:45,Wasilla,AK,Oval,3 minutes,Red glowing object over wasilla skies on new y...,1/6/17
97,12/31/16 20:30,Wasilla,AK,Circle,,Lights in the sky.,1/6/17
98,12/23/16 18:10,Delta Junction,AK,Fireball,45 seconds,Seven fireball glowing/pulsating objects were ...,12/30/16
99,12/22/16 04:15,Anchorage,AK,Unknown,17:00,I looked out of my north facing window after a...,4/8/19

## Export to .csv

In [31]:
key = 'c1eaf3fa7dfd9087a7bbb5f695f9cd'
key_exchange = 'c1b9fa'
email = 'nickcan2296@gmail.com'

b'<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n'

In [57]:
df.to_csv('ufo.csv')

## Sample Questions:

### 1: What City has the most UFO reportings? State?

In [74]:
all_data = df
new_col = all_data['City'] + ', ' + all_data['State']
new_col.columns = ['CityState']
new_col.mode()

0    Las Vegas, NV
1      Phoenix, AZ
dtype: object

In [75]:
all_data['State'].mode()

0    CA
dtype: object